version: "3"

services:
  frontend:
    build: ./frontend 
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: . 
    container_name: backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "4000:4000"
    


